from rsf.proj import *

nt = 1500 # number of samples in the time axis
k1 = 80 # position of the wavelet center
dt = 0.001 # time sampling rate

Flow('spike',None,'spike n1=%d d1=%e k1=%d' % (nt,dt,k1))
Flow('wavelet','spike','ricker1 freq=0.2' )
Result('wavelet','graph')

xmax = 2.0
zmax = 2.0
"""
layers = ((0.30,0.50,0.20,0.30),
          (0.55,0.75,0.45,0.55),
#          (0.55,0.75,0.47,0.6),
          (0.65,0.85,0.55,0.65),
          (1.30,1.30,1.60,1.20))
"""
layers = ((0.70,0.70,0.70,0.70),
          (1.70,1.70,1.70,1.70),
          (2.70,2.70,2.70,2.70))

"""
velocities = (1.508,
              1.581,
              1.690,
              1.826,
              2.000)
"""

velocities = (1.508,
              1.826,
              2.000)
def arr2str(array,sep=' '):
    return string.join(map(str,array),sep)

vstr = arr2str(velocities,',')

n1 = len(layers[0])
n2 = len(layers)

Flow('layers.asc',None,
     '''
     echo %s
     n1=%d n2=%d o1=0 d1=%g
     data_format=ascii_float in=$TARGET
     ''' % (string.join(map(arr2str,layers),' '),
            n1,n2,xmax/(n1-1)))
Flow('layers','layers.asc','dd form=native')

d = 0.0100 # non-round for reproducibility

Flow('refs','layers',
     'spline o1=0 d1=%g n1=%d' % (d,int(xmax/d)))
Flow('dips','refs','deriv scale=y')

Flow('campoVel','refs',
     '''
     unif2 d1=%g n1=%d v00=%s
     ''' % (d,int(zmax/d),vstr))

Result('campoVel',
       '''
       grey color=j title="Model 1"
       screenratio=%g screenht=4
       mean=y titlesz=8 labelsz=6
       label1="Depth (km)"
       label2="Distance (km)"
       ''' % (zmax/xmax))

#Flow('snaps','wavelet',"./fdiffmod vel=campoVel.rsf")
Flow('snaps',['wavelet','campoVel'],"./fdiffmod wav=${SOURCES[0]} vel=${SOURCES[1]}")
Result('snaps','grey color=h')


End()
