from rsf.proj import *

nt = 1900 # number of samples in the time axis
k1 = 80 # position of the wavelet center
dt = 0.001 # time sampling rate

Flow('spike',None,'spike n1=%d d1=%e k1=%d' % (nt,dt,k1))
Flow('wavelet','spike','ricker1 frequency=20')
#Result('wavelet','graph')

# Wavelet
   #Flow('wavelet',None,
   # '''
   # spike n1=700 d1=0.001 k1=80 |
   # ricker1 frequency=20
   # ''')
Result('wavelet','wiggle poly=y pclip=100 title=Wavelet')

xmax = 2.0
zmax = 2.0
"""
layers = ((0.30,0.50,0.20,0.30),
          (0.55,0.75,0.45,0.55),
#          (0.55,0.75,0.47,0.6),
          (0.65,0.85,0.55,0.65),
          (1.30,1.30,1.60,1.20))
"""
layers = ((0.40,0.20,0.90,0.30),
          (1.90,1.30,1.10,1.70),
          (2.90,2.70,2.70,2.70))

"""
velocities = (1.508,
              1.581,
              1.690,
              1.826,
              2.000)
"""

velocities = (2.000,
              3.000,
              4.000)
def arr2str(array,sep=' '):
    return string.join(map(str,array),sep)

vstr = arr2str(velocities,',')

n1 = len(layers[0])
n2 = len(layers)

Flow('layers.asc',None,
     '''
     echo %s
     n1=%d n2=%d o1=0 d1=%g
     data_format=ascii_float in=$TARGET
     ''' % (string.join(map(arr2str,layers),' '),
            n1,n2,xmax/(n1-1)))
Flow('layers','layers.asc','dd form=native')

d = 0.0100 # non-round for reproducibility


nz = int(zmax/d)
nx = int(xmax/d)

Flow('refs','layers',
     'spline o1=0 d1=%g n1=%d' % (d,nx))
Flow('dips','refs','deriv scale=y')

Flow('campoVel','refs',
     '''
     unif2 d1=%g n1=%d v00=%s
     ''' % (d,nx,vstr))

Result('campoVel',
       '''
       grey color=j title="Model 1"
       screenratio=%g screenht=4
       mean=y titlesz=8 labelsz=6
       label1="Depth (km)"
       label2="Distance (km)"
       ''' % (zmax/xmax))


number_src = 9
dist_src = xmax / float(number_src+1)

sx = [dist_src]
for i in range(number_src-1):
    sx.append(sx[i] + dist_src)

nr = (dist_src / d) * 2.0 - 1

dataNames = []

for i in range(len(sx)):
    gxbeg = sx[i] - dist_src
    Flow(['data%d' % i,'snaps%d' % i],['wavelet','campoVel'],"""
./exe wav=${SOURCES[0]} vel=${SOURCES[1]} snaps=${TARGETS[1]}
 sx=%e sz=0.0000 gxbeg=%e gzbeg=0.000 jgx=%e nr=%d""" % (sx[i],gxbeg,d,nr))
    Plot('data%d' % i,
     '''
     grey gainpanel=a title=Wave
     label1=Time label2=Distance unit1=s unit2=m
     ''')
    dataNames.append('data%d' % i)

Result('snaps4',
     '''
     grey gainpanel=a title=Wave
     label1=Depth label2=Distance unit1=m unit2=m
     ''')

Result('data',dataNames,'SideBySideAniso')

   #Flow('figure',['snaps','campoVel'],"""
   #    sfpgreywfl bg=${SOURCES[1]} wflcmap=seismic title="Wavefield" barlabel="Velocity (m/s)" tmin=0.08 savefile=figure.gif""",stdout=-1)


End()
